services:
  # nom du service
  api:
    # construction de notre image
    build:
      # à partir du répertoire ./api
      context: ./api
      # on utilise le fichier Dockerfile.api
      dockerfile: Dockerfile.api
    # on expose le port 3000 du conteneur sur notre port 3000
    ports:
      - 3000:3000
    # le service api dépend du service db
    depends_on:
      - db
    # on nomme le conteneur parce qu'on fait les choses proprement
    container_name: okanban-api
    environment:
      - DB_URL=postgres://okanban:okanban@db:5432/okanban
      - JWT_SECRET=demande-a-chris-le-sysadmin-de-la-promo


      # nom du service
  client:
    # construction de l'image du service
    build:
      # à partir du répertoire ./client
      context: ./client
      # on utilise le fichier Dockerfile.cli
      dockerfile: Dockerfile.client
    # on expose le port 4173 du conteneur sur notre port 4173
    ports:
      - 4173:4173
    # notre service ne démarre que quand le service api est prêt
    depends_on:
      - api
    # on nomme notre conteneur pour savoir qui il est
    container_name: okanban-cli


      # nom du service
  db:
    # on utilise l'image postgres
    image: postgres:17-alpine
    # nom du conteneur
    container_name: okanban-database
    # environnement : on déclare les infos nécessaires à notre BDD
    env_file:
      - .database.docker.env
    # on monte les volumes
    volumes:
      # répertoire des scripts d'initialisation
      - ./api/data:/docker-entrypoint-initdb.d
      # volume de persistance des données
      - pg-okanban:/var/lib/postgresql/data

# ne pas oublier les volumes de persistance utilisés
volumes:
  pg-okanban: